spring:
  application:
    name: cnb-springboot

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
server:
  port: ${PORT:8080}

app:
  message: Hello Spring Boot @ ... at 12:00 PM !
  title: Spring Boot with Cloud-native Buildpacks
