management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
server:
  port: ${PORT:8080}

app:
  message: Hello Spring Boot - local demo with Tanzu Build Service - from the rel-1.0.0 branch!
  title: Spring Boot with Cloud-native Buildpacks
